name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
                    - name: Okteto Test
  # You may pin to the exact commit or the version.
  # uses: okteto/test@8602adbf436da99d8b47d6ccd080e07d88fa52cc
  uses: okteto/test@latest
  with:
    # The name of the dev environment
    name: # optional, default is 
    # The namespace scope for this action. Defaults to the current context if not specified.
    namespace: # optional, default is 
    # Path to the Okteto manifest file. Defaults to the default path if not specified.
    file: # optional, default is 
    # Deploy the dev environment even if it has already been deployed
    deploy: # optional, default is false
    # Do not use the cache when running the tests
    no-cache: # optional, default is false
    # Variables to be used by the dev environment. If multiple variables are present, separate them with commas (e.g., VAR1=VAL1,VAR2=VAL2)
    variables: # optional, default is 
    # The length of time to wait for completion (e.g., 1s, 2m, 3h)
    timeout: # optional, default is 5m
    # The test sections to run, separated by spaces. Runs all tests if no tests are defined (e.g., 'unit integration').
    tests: # optional, default is 
    # Log level for the action. Valid options: debug, info, warn, error.
    log-level: # optional, default is 
          

    - name: Build
      run: |
        npm install
        grunt
